---
title: Errore "Il record di eccezione DataStoreException non esiste" generato in modalità standby a freddo
description: Descrizione
solution: Experience Manager
product: Experience Manager
applies-to: Experience Manager
keywords: KCS, AEM, standby a freddo, DataStoreException, Adobe Experience Manager, il record non esiste, errore, avviso, avviso
resolution: Resolution
internal-notes: https://issues.apache.org/jira/browse/OAK-8202,https://jira.corp.adobe.com/browse/GRANITE-11668
bug: false
article-created-by: Jim Menn
article-created-date: 9/28/2022 2:23:47 PM
article-published-by: Jim Menn
article-published-date: 9/28/2022 5:41:23 PM
version-number: 3
article-number: KA-15610
dynamics-url: https://adobe-ent.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=entityrecord&etn=knowledgearticle&id=5e521024-393f-ed11-9db1-0022480866ad
exl-id: d37d0338-be4f-4660-a4b2-cd1179717e07
source-git-commit: 4702b69f883128bf305ec64f012ef01903f3f582
workflow-type: tm+mt
source-wordcount: '231'
ht-degree: 1%

---

# Errore &quot;Il record di eccezione DataStoreException non esiste&quot; generato in modalità standby a freddo

## Descrizione


<b>Ambiente</b>
Adobe Experience Manager

<b>Problema</b>
Lo standby a freddo con archivio dati file dedicato genera un avviso sull’ID BLOB mancante simile all’errore qui:


```
*WARN* standby-run-1 org.apache.jackrabbit.oak.plugins.blob.datastore.DataStoreBlobStore Error occurred while loading bytes from steam while fetching for id f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a1845#25522

java.util.concurrent.ExecutionException: java.io.IOException: org.apache.jackrabbit.core.data.DataStoreException: Record f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a1845 does not exist

    at org.apache.jackrabbit.oak.cache.CacheLIRS$Segment.load(CacheLIRS.java:1017) org.apache.jackrabbit.oak-core-spi:1.10.3

...

Caused by: org.apache.jackrabbit.core.data.DataStoreException: Record cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20 does not exist

    at org.apache.jackrabbit.core.data.AbstractDataStore.getRecord(AbstractDataStore.java:59)
```


<b>Causa</b>
Questo è solo un avviso, non un errore.

Deriva dal fatto che il file datastore non ha modo di verificare se esiste localmente un binario, se non tentando di caricare l’ID BLOB.
Se l’ID viene caricato, i registri non mostrano questo avviso.
Tuttavia, se non viene trovato, lo standby sa che deve sincronizzarlo, quindi questo è il motivo per cui si vede questo tipo di avviso nei registri.


## Risoluzione


<b>Soluzione</b>
Questo funziona come previsto e non indica un problema con il file datastore.

Per verificare che l’ID BLOB non sia effettivamente mancante, effettua le seguenti operazioni:

1. Ad esempio, considera l’ID BLOB di esempio che viene visualizzato come mancante nei registri (ad esempio: `cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`).
2. Per questo ID BLOB in questo esempio, l’indirizzo del file system deve essere: `ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`.
3. Cercare il file system nell&#39;istanza in standby e verificare se il file denominato è presente nell&#39;archivio dati dei file.
4. Entro `/repository/datastore`, utilizza `list` Ad esempio: `ls -ald`) comando: `ls -ald ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20`.
5. Dovresti essere in grado di visualizzare il file e confermare che l’ID BLOB non sia effettivamente mancante.
